services:
  mysql:
    image: mysql:8.0
    container_name: mysql-test
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: jungi1234	# 구성활 MySQL의 root 비밀번호
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: board-test		# 기본으로 생성할 database명
    volumes:
      - ./db/mysql-test/data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'